spring.application.name=review-analyzer

spring.datasource.url=jdbc:postgresql://localhost:5432/analytics
spring.datasource.username=postgres
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto= create-drop

spring.jpa.show-sql=true

# ????????? ??? ??????????? ? Mistral AI API
mistral.api.key=yw9iz1peDCATK25kbQm1LGEbNUfvH0QW
mistral.api.url=https://api.mistral.ai/v1/chat/completions
# ????? ???????, ?????? ? ?????????? ??? ????????????? ?????? ? Mistral
mistral.api.model=open-mistral-7b

spring.jpa.open-in-view=false